-- P6-2B: Shadow trading signal observation table.
-- Stores signals generated by promoted strategies BEFORE they enter paper trading.
-- Used to observe signal quality over 7 trading days without any execution.

CREATE TABLE IF NOT EXISTS shadow_signals (
    id BIGSERIAL PRIMARY KEY,
    exchange TEXT NOT NULL,
    symbol TEXT NOT NULL,
    mode TEXT NOT NULL CHECK (mode IN ('long_only', 'long_short')),
    signal_value DOUBLE PRECISION NOT NULL,
    signal_timestamp TIMESTAMPTZ NOT NULL,
    genome INTEGER[] NOT NULL,
    generation INTEGER NOT NULL,
    threshold_config JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for querying shadow signals by strategy
CREATE INDEX IF NOT EXISTS idx_shadow_signals_strategy
    ON shadow_signals (exchange, symbol, mode, signal_timestamp DESC);

-- Add shadow status to deployed_strategies lifecycle
-- Status flow: shadow → paper → live (manual)
-- Already has 'active' and 'replaced'; add 'shadow' as a valid status
ALTER TABLE deployed_strategies
    ADD COLUMN IF NOT EXISTS shadow_started_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS shadow_trading_days INTEGER NOT NULL DEFAULT 0;

COMMENT ON TABLE shadow_signals IS
    'P6-2B: Signal-only observation before paper trading. 7 trading days mandatory.';
COMMENT ON COLUMN deployed_strategies.shadow_started_at IS
    'Timestamp when strategy entered shadow observation mode';
COMMENT ON COLUMN deployed_strategies.shadow_trading_days IS
    'Count of completed trading days in shadow mode (target: 7)';
