use std::collections::HashMap;

/// Operator name table indexed by op_idx (= token - feat_offset).
/// Covers all 14 active operators used by the current GA; legacy opcodes
/// (NEG, GATE, SIGNED_POWER, etc.) are included for decoding stored genomes
/// but are never generated by `encode_formula`.
const OP_NAMES: &[(usize, &str)] = &[
    (0, "ADD"),
    (1, "SUB"),
    (2, "MUL"),
    (3, "DIV"),
    (4, "NEG"),
    (5, "ABS"),
    (6, "SIGN"),
    (7, "GATE"),
    (8, "SIGNED_POWER"),
    (9, "DECAY_LINEAR"),
    (10, "DELAY1"),
    (11, "DELAY5"),
    (12, "TS_MEAN"),
    (13, "TS_STD"),
    (14, "TS_RANK"),
    (15, "TS_SUM"),
    (16, "TS_CORR"),
    (17, "TS_MIN"),
    (18, "TS_MAX"),
    (19, "LOG"),
    (20, "SQRT"),
    (21, "TS_ARGMAX"),
    (22, "TS_DELTA"),
];

/// Classify a token's arity (mirrors `genetic.rs::token_arity`).
fn token_arity(token: usize, feat_offset: usize) -> usize {
    if token < feat_offset {
        return 0; // feature pushes to stack
    }
    let op_idx = token - feat_offset;
    match op_idx {
        0..=3 | 16 => 2, // binary: ADD, SUB, MUL, DIV, TS_CORR
        7 => 3,          // ternary: GATE (legacy)
        _ => 1,          // unary: everything else
    }
}

/// Convert a single token index to its human-readable name.
pub fn token_to_name(token: usize, feat_offset: usize, factor_names: &[String]) -> String {
    if token < feat_offset {
        if token < factor_names.len() {
            factor_names[token].clone()
        } else {
            format!("f{}", token)
        }
    } else {
        let op_idx = token - feat_offset;
        OP_NAMES
            .iter()
            .find(|(idx, _)| *idx == op_idx)
            .map(|(_, name)| name.to_string())
            .unwrap_or_else(|| format!("OP{}", op_idx))
    }
}

/// Decode a genome's token array into an RPN formula string.
///
/// Example: tokens `[0, 6, 12, 25]` with feat_offset=25 →
///   `"return momentum TS_MEAN ADD"`
pub fn decode_genome(tokens: &[usize], feat_offset: usize, factor_names: &[String]) -> String {
    tokens
        .iter()
        .map(|&t| token_to_name(t, feat_offset, factor_names))
        .collect::<Vec<_>>()
        .join(" ")
}

/// Parse an RPN formula string back into a token array.
///
/// Returns `None` if any token name is unrecognized.
pub fn encode_formula(
    formula: &str,
    feat_offset: usize,
    factor_names: &[String],
) -> Option<Vec<usize>> {
    let name_to_feature: HashMap<&str, usize> = factor_names
        .iter()
        .enumerate()
        .map(|(i, name)| (name.as_str(), i))
        .collect();

    let name_to_op: HashMap<&str, usize> = OP_NAMES
        .iter()
        .map(|(idx, name)| (*name, idx + feat_offset))
        .collect();

    let mut tokens = Vec::new();
    for part in formula.split_whitespace() {
        if let Some(&feat_idx) = name_to_feature.get(part) {
            tokens.push(feat_idx);
        } else if let Some(&op_token) = name_to_op.get(part) {
            tokens.push(op_token);
        } else {
            return None; // unrecognized token
        }
    }

    Some(tokens)
}

/// Validate that an RPN token sequence is stack-correct.
///
/// A valid formula:
/// 1. Never underflows the stack (depth >= 0 at all points)
/// 2. Ends with exactly 1 item on the stack
/// 3. Has at least 1 token
/// 4. Does not exceed max length (20 tokens)
pub fn validate_stack(tokens: &[usize], feat_offset: usize) -> Result<(), StackError> {
    if tokens.is_empty() {
        return Err(StackError::Empty);
    }
    if tokens.len() > 20 {
        return Err(StackError::TooLong(tokens.len()));
    }

    let mut depth: i32 = 0;
    for (i, &token) in tokens.iter().enumerate() {
        if token < feat_offset {
            depth += 1;
        } else {
            let arity = token_arity(token, feat_offset) as i32;
            depth = depth - arity + 1;
        }
        if depth < 1 && i < tokens.len() - 1 {
            return Err(StackError::Underflow { position: i });
        }
    }

    if depth != 1 {
        return Err(StackError::FinalDepth(depth));
    }

    Ok(())
}

#[derive(Debug)]
pub enum StackError {
    Empty,
    TooLong(usize),
    Underflow { position: usize },
    FinalDepth(i32),
}

impl std::fmt::Display for StackError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Empty => write!(f, "empty formula"),
            Self::TooLong(n) => write!(f, "formula too long ({} tokens, max 20)", n),
            Self::Underflow { position } => write!(f, "stack underflow at position {}", position),
            Self::FinalDepth(d) => write!(f, "final stack depth {} (expected 1)", d),
        }
    }
}

/// Build the list of operator names that the GA actively generates.
/// Used in LLM prompts to tell the model which operators are available.
#[allow(dead_code)]
pub fn active_operator_names() -> Vec<&'static str> {
    vec![
        "ADD", "SUB", "MUL", "DIV", // binary
        "ABS", "SIGN", "DELAY1", "DELAY5", "TS_MEAN", "TS_STD", "TS_RANK", "TS_MIN",
        "TS_MAX",  // unary
        "TS_CORR", // binary
    ]
}

/// Build a description of operators for the LLM prompt.
pub fn operator_descriptions() -> Vec<(&'static str, &'static str, &'static str)> {
    vec![
        ("ADD", "binary", "a + b"),
        ("SUB", "binary", "a - b"),
        ("MUL", "binary", "a * b"),
        ("DIV", "binary", "a / b (safe division)"),
        ("ABS", "unary", "|a|"),
        ("SIGN", "unary", "sign(a): -1, 0, or 1"),
        ("DELAY1", "unary", "value from 1 bar ago"),
        ("DELAY5", "unary", "value from 5 bars ago"),
        ("TS_MEAN", "unary", "20-bar rolling mean"),
        ("TS_STD", "unary", "20-bar rolling std dev"),
        ("TS_RANK", "unary", "percentile rank over 20 bars"),
        ("TS_MIN", "unary", "20-bar rolling minimum"),
        ("TS_MAX", "unary", "20-bar rolling maximum"),
        ("TS_CORR", "binary", "20-bar rolling correlation"),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_factors() -> Vec<String> {
        vec![
            "return",
            "vwap_deviation",
            "volume_ratio",
            "mean_reversion",
            "adv_ratio",
            "volatility",
            "momentum",
            "relative_strength",
            "close_position",
            "intraday_range",
            "vol_regime",
            "trend_strength",
            "momentum_regime",
            "atr_pct",
            "obv_pct",
            "mfi",
            "bb_percent_b",
            "macd_hist",
            "sma_200_diff",
            "amihud_illiq",
            "spread_proxy",
            "return_autocorr",
            "spy_corr",
            "spy_beta",
            "spy_rel_strength",
        ]
        .into_iter()
        .map(String::from)
        .collect()
    }

    #[test]
    fn test_decode_simple() {
        let factors = test_factors();
        let feat_offset = 25;
        // return momentum TS_MEAN
        let tokens = vec![0, 6, feat_offset + 12];
        let decoded = decode_genome(&tokens, feat_offset, &factors);
        assert_eq!(decoded, "return momentum TS_MEAN");
    }

    #[test]
    fn test_decode_binary_op() {
        let factors = test_factors();
        let feat_offset = 25;
        // close_position volatility ADD
        let tokens = vec![8, 5, feat_offset + 0];
        let decoded = decode_genome(&tokens, feat_offset, &factors);
        assert_eq!(decoded, "close_position volatility ADD");
    }

    #[test]
    fn test_encode_round_trip() {
        let factors = test_factors();
        let feat_offset = 25;
        let original = "return momentum TS_MEAN volume_ratio MUL";
        let tokens = encode_formula(original, feat_offset, &factors).unwrap();
        let decoded = decode_genome(&tokens, feat_offset, &factors);
        assert_eq!(decoded, original);
    }

    #[test]
    fn test_encode_unknown_token() {
        let factors = test_factors();
        let feat_offset = 25;
        let result = encode_formula("return BOGUS_OP", feat_offset, &factors);
        assert!(result.is_none());
    }

    #[test]
    fn test_validate_stack_valid() {
        let feat_offset = 25;
        // feature feature binary_op → depth: 1,2,1 → valid
        let tokens = vec![0, 1, feat_offset + 0]; // f0 f1 ADD
        assert!(validate_stack(&tokens, feat_offset).is_ok());
    }

    #[test]
    fn test_validate_stack_single_feature() {
        let feat_offset = 25;
        let tokens = vec![0]; // just f0
        assert!(validate_stack(&tokens, feat_offset).is_ok());
    }

    #[test]
    fn test_validate_stack_unary_chain() {
        let feat_offset = 25;
        // f0 ABS TS_MEAN → depth: 1,1,1 → valid
        let tokens = vec![0, feat_offset + 5, feat_offset + 12];
        assert!(validate_stack(&tokens, feat_offset).is_ok());
    }

    #[test]
    fn test_validate_stack_underflow() {
        let feat_offset = 25;
        // ADD f0 → starts with binary op, pops 2 from empty stack
        let tokens = vec![feat_offset + 0, 0];
        assert!(validate_stack(&tokens, feat_offset).is_err());
    }

    #[test]
    fn test_validate_stack_too_many_on_stack() {
        let feat_offset = 25;
        // f0 f1 → depth 2, not collapsed
        let tokens = vec![0, 1];
        let result = validate_stack(&tokens, feat_offset);
        assert!(result.is_err());
        match result.unwrap_err() {
            StackError::FinalDepth(d) => assert_eq!(d, 2),
            e => panic!("expected FinalDepth, got {:?}", e),
        }
    }

    #[test]
    fn test_validate_stack_empty() {
        let feat_offset = 25;
        let result = validate_stack(&[], feat_offset);
        assert!(result.is_err());
    }

    #[test]
    fn test_validate_stack_too_long() {
        let feat_offset = 25;
        let tokens: Vec<usize> = (0..21).collect(); // 21 features
        let result = validate_stack(&tokens, feat_offset);
        assert!(result.is_err());
        match result.unwrap_err() {
            StackError::TooLong(n) => assert_eq!(n, 21),
            e => panic!("expected TooLong, got {:?}", e),
        }
    }

    #[test]
    fn test_complex_formula_round_trip() {
        let factors = test_factors();
        let feat_offset = 25;
        // (momentum - TS_MEAN(volume_ratio)) → momentum volume_ratio TS_MEAN SUB
        let formula = "momentum volume_ratio TS_MEAN SUB";
        let tokens = encode_formula(formula, feat_offset, &factors).unwrap();
        assert!(validate_stack(&tokens, feat_offset).is_ok());
        let decoded = decode_genome(&tokens, feat_offset, &factors);
        assert_eq!(decoded, formula);
    }

    #[test]
    fn test_active_operator_names() {
        let names = active_operator_names();
        assert_eq!(names.len(), 14);
        assert!(names.contains(&"ADD"));
        assert!(names.contains(&"TS_CORR"));
        assert!(!names.contains(&"GATE")); // legacy, not active
    }
}
