global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "data-service"
    static_configs:
      - targets: ["data-service:8000"]

  - job_name: "trading-engine"
    static_configs:
      - targets: ["trading-engine:8001"]

  - job_name: "strategy-engine"
    static_configs:
      - targets: ["strategy-engine:8002"]

  - job_name: "risk-control"
    static_configs:
      - targets: ["risk-control:8003"]

  - job_name: "execution-service"
    static_configs:
      - targets: ["execution-service:8004"]

  - job_name: "account-service"
    static_configs:
      - targets: ["account-service:8005"]

  - job_name: "security-service"
    static_configs:
      - targets: ["security-service:8006"]

  - job_name: "report-service"
    static_configs:
      - targets: ["report-service:8007"] 